name: pancancer-classifier
channels:
- r
- bioconda
dependencies:
- bioconda::r-checkpoint=0.4.0
- anaconda::jupyter=1.0.0
- anaconda::numpy=1.11.2
- anaconda::pandas=0.20.3
- anaconda::scikit-learn=0.18.1
- anaconda::seaborn=0.8.1
- anaconda::python=3.5.2
- anaconda::statsmodels=0.8.0
- anaconda::numexpr=2.6.2
- conda-forge::plotnine=0.2.1
- conda-forge::dask-searchcv=0.0.2

